{% set name = "topoflow-diversions-fraction-method-csdms" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/topoflow-bridge

requirements:
  build:
    - bmi-babel
    - topoflow
  run:
    - bmi-babel
    - topoflow

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Diversions
  license: Apache
  summary: |
    The DiversionsFractionMethod component is a part of the
    spatially distributed hydrologic model TopoFlow. TopoFlow supports
    three different types of flow diversions: sources, sinks, and
    canals. Sources are point locations, such as natural springs, where
    water enters the watershed. Sinks are point locations where water
    leaves the watershed. Canals are man-made reaches such as tunnels or
    irrigation ditches that transport water from one point to another,
    typically without following the natural gradient of the terrain that
    is indicated by the DEM. The upstream end of a canal is essentially
    a sink and the downstream end a source.
